Decouple forms
kadaster-labs/sensrnet-registry-frontend pull request #96
Opened 2020-09-24 07:02 UTC by kad-floriw

- Wanneer je een owner update, wordt een aparte pagina geopend
- Eerste stappen gemaakt voor het meer modulair maken van de applicatie
- Initieel worden sensoren opgehaald met GET /Sensors. Dit is nodig omdat je niet iedere keer een nieuwe websocket verbinding op wilt zetten als je de viewer component bezoekt.
- JWT authenticatie voor websocket verbindingen

2020-09-24 10:35 UTC, kad-busses reviewed
Ziet er goed uit! Goed om de pagina los te trekken uit de viewer. Is inderdaad de richting waarin we moeten gaan, zoals we ook vanochtend besproken hebben.

Nog een puntje: ik zie dat er worden nu linting error geïntroduceerd en regels aangepast die geen probleem waren. Zou je je editor willen instellen dat die gebruikt maakt van de linting rules van het project? 😊 Scheelt ook weer tijd tijdens de review

2020-09-24 14:37 UTC, kad-floriw commented
@kad-busses Goed punt, TSlint had ik al, maar om ESlint te laten werken binnen webstorm moet je die blijkbaar includen als devdependency.

2020-09-30 09:05 UTC, kad-floriw commented
@kad-busses Ik heb alle functionaliteiten getest, maar misschien wil jij er nog even goed naar kijken of je nog opmerkingen hebt. Het zou mooi zijn als we het vandaag kunnen mergen

2020-09-30 11:45 UTC, kad-floriw commented
![Untitled2](https://user-images.githubusercontent.com/53855759/94681118-30a83200-0323-11eb-9803-ac5129d66830.png)

2020-09-30 13:17 UTC, kad-busses requested changes
Ziet er goed uit Wim! De tabel is een goede toevoeging, leuk om te zien dat het sorteren ook al werkt. Mooi dat de map nu een losse component is, geeft ons veel meer flexibiliteit 😁 De aparte pagina's bieden een mooie basis voor de extra toe te voegen functionaliteit!

#### Functionaliteit
Bij het testen kwam ik eigenlijk maar 1 klein dingetje tegen. Ik zag dat de functionaliteit van de theme selector op de Update sensor pagina niet meer werkt, die wordt niet meer gevuld met de waarden die de sensor al heeft. Wil je die nog even fixen?

#### UI
Qua interface heb ik de volgende puntjes:
- Bij updaten owner schuift pagina naar beneden (daar was een success alert)
- Menu mag weer dichtgeklapt door op 'Menu' te klikken, gaat nu altijd naar Owner
- Dubbele item namen in menu: 3x Sensor(s). Daar kan het beste ook in tekst bijgevoegd worden welke functionaliteit daar te vinden is
- Het lijkt netter als we bij de items de icons in-line zetten met de labels
- Logout knop kan ook in menu en uit kaart voor een extra cleane layout 🙂
- "Zoeken in SensRNet" is verwarrend, impliceert zoeken naar sensoren in het register ipv gebieden op de kaart
- Ik ben geen fan van de kaart in volledige hoogte naast het formulier te zetten. De kaart is eigenlijk ook maar nodig bij 1 invoerveld: de locatie. Daarom hoeft die straks maar op 1 page zichtbaar te zijn van het multi-page formulier. Laat nu eerst maar staan, want de multi-page form komt later pas 😉

2020-09-30 13:31 UTC, kad-floriw commented on src/app/services/connection.service.ts
> +export class ConnectionService {
Dat was eerst zo, maar dat werkt niet omdat ze elkaar nodig hebben (circular dependency). En omdat ze beide vergelijkbare functionaliteit aanbieden (geauthenticeerde requests naar de backend) en niet te groot zijn, heb ik ze samengevoegd.

2020-09-30 13:48 UTC, kad-floriw commented on src/app/components/map/map.component.html
> +        <div id="popup" class="ol-popup bg-white border-0 hidden">
Lijkt mij mooi voor een volgende pr

2020-09-30 13:54 UTC, kad-floriw commented on src/app/services/connection.service.ts
> +export class ConnectionService {
Heb jij een idee hoe dat te refactoren is? Authservice moet websockets kunnen sluiten, en Dataservice moet kunnen uitloggen. Of even zo laten voor nu, en dan later nog eens kijken.

2020-09-30 14:30 UTC, kad-floriw commented
@kad-busses Goede feedback! Alleen het authservice / websocket puntje zo ik ieg voor nu zo willen laten, om dat deze componenten een 1-op-1 relatie hebben stel dat ze ontkoppelt zijn. Voor de rest heb ik de punten verwerkt omdat dat mooie verbeteringen zijn. Ter-info voor de sidebar had ik inspiratie opgedaan bij de youtube sidebar als die ingeklapt is, die vond ik er mooi uitzien ;)

2020-10-01 09:04 UTC, kad-busses approved these changes
Looking good! Nice dat je Youtube als inspiratie hebt gebruikt, die hebben inderdaad een mooie sidebar. Zie nog 1 linter melding, maar laat eerst maar staan. Authentication en SocketIO services komen we later wel op terug, wmb gaan we dit eerst mergen.

Viel me net trouwens ook op dat de mouse-position dubbel is, die staat zowel naast de schaalbalk als rechts bovenin op kaart 🙈

2020-10-01 09:07 UTC, merged